"""empty message

Revision ID: 26cdc659172e
Revises: 984172786a55
Create Date: 2017-11-30 01:14:30.840660

"""

# revision identifiers, used by Alembic.
revision = '26cdc659172e'
down_revision = '984172786a55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('played', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('played', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
