"""empty message

Revision ID: 512c3b11e4ad
Revises: 26cdc659172e
Create Date: 2017-11-30 04:10:13.781936

"""

# revision identifiers, used by Alembic.
revision = '512c3b11e4ad'
down_revision = '26cdc659172e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'result')
    # ### end Alembic commands ###
